"""Render a cleaning run (recipe + change log + before/after) as HTML or Markdown."""

from __future__ import annotations

from datetime import datetime, timezone
from html import escape

from spreadsheet_cleaner.clean import CleanResult
from spreadsheet_cleaner.core.models import QualityReport
from spreadsheet_cleaner.report.html import _CSS, _score_class


def _recipe_lines(result: CleanResult) -> list[str]:
    lines = []
    for step in result.recipe.steps:
        cols = step.columns if step.columns == "all" else ", ".join(step.columns)
        extra = " ".join(f"{k}={v}" for k, v in step.params.items())
        lines.append(f"{step.type} [{cols}]" + (f" ({extra})" if extra else ""))
    return lines


def to_html(
    result: CleanResult,
    before: QualityReport | None = None,
    after: QualityReport | None = None,
) -> str:
    log = result.changelog
    now = datetime.now(timezone.utc)

    ba = ""
    if before is not None and after is not None:
        bcls, acls = _score_class(before.score), _score_class(after.score)
        ba = f"""
<div class="section"><h2>Before and after</h2></div>
<div class="grid">
  <div class="card dim"><div class="top"><span class="name">Before</span>
    <span class="val g-{bcls}" style="padding:0 8px;border-radius:8px">{before.grade}</span></div>
    <div class="foot">{before.score:.0f} / 100 · {before.rows:,} rows · {before.cols} cols</div></div>
  <div class="card dim"><div class="top"><span class="name">After</span>
    <span class="val g-{acls}" style="padding:0 8px;border-radius:8px">{after.grade}</span></div>
    <div class="foot">{after.score:.0f} / 100 · {after.rows:,} rows · {after.cols} cols</div></div>
  <div class="card dim"><div class="top"><span class="name">Changes</span>
    <span class="val">{log.total_changes:,}</span></div>
    <div class="foot">{log.rows_removed} row(s), {log.cols_removed} column(s) removed</div></div>
</div>"""

    rows = []
    for r in log.records:
        col = f'<span class="tag dim">{escape(r.column)}</span>' if r.column else '<span class="tag dim">table</span>'
        samples = ""
        if r.samples:
            chips = "".join(
                f"<code>{escape(str(b))}</code> &rarr; <code>{escape(str(a))}</code>"
                for b, a in r.samples
            )
            samples = f'<div class="samples">{chips}</div>'
        rows.append(f"""
<div class="card finding info">
  <div class="ftop">
    <span class="tag info">{escape(r.step)}</span>{col}
    <span class="ttl">{r.changed:,} change(s)</span>
  </div>
  <div class="det">{escape(r.detail)}</div>
  {samples}
</div>""")
    log_html = "".join(rows) or '<div class="card clean">No changes were needed.</div>'

    recipe_html = "<br>".join(escape(line) for line in _recipe_lines(result))

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Cleaning Report - Spreadsheet Cleaner</title>
<style>{_CSS}</style></head>
<body><div class="wrap">
<div class="card head">
  <div>
    <div class="eyebrow">Cleaning Report</div>
    <h1>Spreadsheet Cleaner</h1>
    <div class="meta">Source: <code>{escape(result.source)}</code><br>
      {log.total_changes:,} change(s) across {len(log.records)} step result(s)<br>
      Generated {now:%Y-%m-%d %H:%M} UTC</div>
  </div>
</div>
{ba}
<div class="section"><h2>Recipe applied</h2>
<p class="sub">Deterministic. Save this recipe and re-run it on the next delivery.</p></div>
<div class="card tablecard"><div class="meta" style="padding:8px 14px;font-family:Consolas,monospace">{recipe_html}</div></div>
<div class="section"><h2>Change log</h2></div>
{log_html}
<div class="foot">Generated by Spreadsheet Cleaner. Fully offline. Your source file was not modified.</div>
</div></body></html>"""


def to_markdown(
    result: CleanResult,
    before: QualityReport | None = None,
    after: QualityReport | None = None,
) -> str:
    log = result.changelog
    now = datetime.now(timezone.utc)
    lines = ["# Cleaning Report", "", f"**Source:** `{result.source}`",
             f"**Generated:** {now:%Y-%m-%d %H:%M UTC}",
             f"**Changes:** {log.total_changes:,} across {len(log.records)} step result(s)", ""]
    if before is not None and after is not None:
        lines += [
            "## Before and after", "",
            f"- Grade: **{before.grade} ({before.score:.0f})** → **{after.grade} ({after.score:.0f})**",
            f"- Rows: {before.rows:,} → {after.rows:,}",
            f"- Columns: {before.cols} → {after.cols}", "",
        ]
    lines += ["## Recipe applied", ""]
    lines += [f"{i + 1}. `{line}`" for i, line in enumerate(_recipe_lines(result))]
    lines += ["", "## Change log", ""]
    if log.is_empty:
        lines.append("No changes were needed.")
    for r in log.records:
        where = r.column or "table"
        lines.append(f"- **{r.step}** on `{where}`: {r.changed:,} change(s). {r.detail}")
    return "\n".join(lines)
