"""Render a QualityReport as a Markdown document."""

from __future__ import annotations

from spreadsheet_cleaner.core.models import DIMENSION_ORDER, QualityReport, Severity

_SEV_MARK = {Severity.ERROR: "🔴", Severity.WARNING: "🟠", Severity.INFO: "🔵"}


def to_markdown(report: QualityReport) -> str:
    lines: list[str] = []
    src = report.source
    lines.append("# Data Quality Report")
    lines.append("")
    lines.append(f"**Source:** `{src}`" + (f" · sheet `{report.sheet}`" if report.sheet else ""))
    lines.append(f"**Generated:** {report.generated_at:%Y-%m-%d %H:%M UTC}")
    lines.append(f"**Rows:** {report.rows:,} · **Columns:** {report.cols}")
    if report.blank_rows_ignored:
        lines.append(f"**Blank rows ignored:** {report.blank_rows_ignored}")
    lines.append("")
    lines.append(f"## Overall: {report.grade} ({report.score:.0f}/100)")
    lines.append("")
    lines.append(f"{report.error_count} error(s) · {report.warning_count} warning(s)")
    lines.append("")

    lines.append("## Quality by dimension")
    lines.append("")
    lines.append("| Dimension | Score | Affected / Checked | What it measures |")
    lines.append("|---|---:|---:|---|")
    for dim in DIMENSION_ORDER:
        stat = report.stat(dim)
        denom = f"{stat.affected:,} / {stat.applicable:,}" if stat.applicable else "n/a"
        lines.append(
            f"| {dim.label} | {stat.score:.0f} | {denom} | {dim.description} |"
        )
    lines.append("")

    lines.append("## Columns")
    lines.append("")
    lines.append("| Column | Type | Fill | Distinct | Unique key |")
    lines.append("|---|---|---:|---:|:---:|")
    for c in report.columns:
        key = "✓" if c.is_unique else ""
        lines.append(
            f"| {c.name} | {c.inferred_type} | {c.fill_rate:.0%} | {c.distinct:,} | {key} |"
        )
    lines.append("")

    lines.append("## Findings")
    lines.append("")
    issues = report.sorted_issues()
    if not issues:
        lines.append("No issues found. This table looks clean. ✅")
    for issue in issues:
        mark = _SEV_MARK[issue.severity]
        lines.append(f"### {mark} {issue.title}")
        lines.append("")
        lines.append(f"*{issue.dimension.label}:* {issue.detail}")
        if issue.samples:
            sample_text = ", ".join(f"`{s}`" for s in issue.samples)
            lines.append("")
            lines.append(f"Examples: {sample_text}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Generated by [Spreadsheet Cleaner]"
        "(https://github.com/michaelnocito/spreadsheet-cleaner), "
        f"v{report.tool_version}. Fully offline. Your data never left this machine."
    )
    return "\n".join(lines)
